version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create .env file
          command: echo REACT_APP_BASE_URL="$REACT_APP_BASE_URL" >> ./.env
      - run:
          name: Build
          command: npm run build --prod
      - run:
          name: modify-firebaserc
          command: sed -i "s/\[YOUR\-PROJECT\-ID\]/$FIREBASE_PROJECT_ID/g" .firebaserc
      - run:
          name: Firebase deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"