export const actionTypes = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  LOGIN_USER_RESET: 'LOGIN_USER_RESET',
  GET_COUNTRIES_AIR: 'GET_COUNTRIES_AIR',
  GET_COUNTRIES_ROAD: 'GET_COUNTRIES_ROAD',
};
