const actionTypes = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  LOGIN_USER_RESET: 'LOGIN_USER_RESET',
  LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
  GET_COUNTRIES_AIR: 'GET_COUNTRIES_AIR',
  GET_COUNTRIES_ROAD: 'GET_COUNTRIES_ROAD',
  CALCULATE_RESET: 'CALCULATE_RESET',
  CALCULATE_SUCCESS: 'CALCULATE_SUCCESS',
  CALCULATE_ERROR: 'CALCULATE_ERROR',
};

export default actionTypes;
