const actionTypes = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  LOGIN_USER_RESET: 'LOGIN_USER_RESET',
  LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
  GET_COUNTRIES_RESET: 'GET_COUNTRIES_RESET',
  GET_COUNTRIES_AIR: 'GET_COUNTRIES_AIR',
  GET_COUNTRIES_ROAD: 'GET_COUNTRIES_ROAD',
  PRICES_AIR_RESET: 'PRICES_AIR_RESET',
  PRICES_AIR_SUCCESS: 'PRICES_AIR_SUCCESS',
  PRICES_AIR_ERROR: 'PRICES_AIR_ERROR',
  PRICES_ROAD_RESET: 'PRICES_ROAD_RESET',
  PRICES_ROAD_SUCCESS: 'PRICES_ROAD_SUCCESS',
  PRICES_ROAD_ERROR: 'PRICES_ROAD_ERROR',
  CALCULATE_RESET: 'CALCULATE_RESET',
  CALCULATE_SUCCESS: 'CALCULATE_SUCCESS',
  CALCULATE_ERROR: 'CALCULATE_ERROR',
};

export default actionTypes;
